import {MigrationInterface, QueryRunner} from "typeorm";

export class FakePosts1633112923220 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Decampitated', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, 0, '2020-10-23T04:17:12Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Charlie''s Angels: Full Throttle', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, 0, '2020-10-04T06:35:30Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Mystery Street', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, 0, '2021-02-07T03:21:48Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Mad About Mambo', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, 0, '2021-07-21T07:52:42Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Philanthropy (Filantropica)', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 0, '2021-01-09T05:48:09Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Bulletproof', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 0, '2021-09-26T21:36:08Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Lower City (Cidade Baixa)', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, 0, '2021-09-30T23:05:36Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Edge of Fear (Ella y el miedo)', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 0, '2020-10-09T07:06:12Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Limbo', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, 0, '2021-09-25T08:09:51Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Night of the Running Man', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, 0, '2021-06-28T12:05:59Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Which Way to the Front?', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 0, '2021-07-23T08:09:18Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Bright Leaves', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, 0, '2021-02-02T15:50:06Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Last Chance Harvey', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 0, '2021-08-05T11:11:12Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Two Kilers (Kilerów 2-óch)', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, 0, '2020-12-23T20:53:19Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Kingdom of Heaven', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, 0, '2021-03-12T10:26:30Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('American Splendor', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, 0, '2021-09-02T16:53:57Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Hamlet, Prince of Denmark', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, 0, '2021-08-26T04:13:13Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Better Living', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, 0, '2020-12-08T04:15:03Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('52 Pick-Up', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 0, '2020-11-14T05:12:01Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Ball of Fire', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, 0, '2021-09-29T03:43:31Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Portrait of Jennie', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, 0, '2021-02-07T15:53:26Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Dirty Dingus Magee', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, 0, '2021-09-24T00:14:15Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Alphabet City', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 0, '2021-01-06T10:58:44Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Half Moon (a.k.a. Niwemang)', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, 0, '2021-03-11T22:38:41Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Look Both Ways', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, 0, '2021-01-04T18:53:55Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Perfume', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, 0, '2021-01-08T12:40:27Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Television Under the Swastika (Das Fernsehen unter dem Hakenkreuz)', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, 0, '2021-05-31T12:02:26Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Stolen Life, A', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 0, '2021-09-08T11:42:04Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Haunted Mansion, The', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, 0, '2021-06-23T13:29:35Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Wrecked', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, 0, '2021-03-16T18:35:24Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Pokémon the Movie 2000', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, 0, '2021-07-11T10:12:49Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Claustrofobia', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, 0, '2021-01-01T23:55:19Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Philomena', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, 0, '2020-12-25T12:10:50Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Fast and the Furious, The', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, 0, '2021-08-21T09:06:52Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Two Weeks in September', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, 0, '2021-04-13T02:10:39Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Millie', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, 0, '2020-10-12T08:23:28Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Morning Patrol (Proini peripolos)', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, 0, '2020-10-19T02:34:18Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Lifeguard, The', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 1, 0, '2021-04-21T16:43:25Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Familiar Ground', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, 0, '2021-06-23T03:50:03Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Manufacturing Consent: Noam Chomsky and the Media', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 0, '2021-07-18T02:51:20Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Bright Leaves', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, 0, '2021-05-16T15:50:22Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Do You Remember Dolly Bell? (Sjecas li se, Dolly Bell)', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, 0, '2021-02-13T13:03:38Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Great Gatsby, The', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, 0, '2020-12-17T17:35:28Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Shiver (Eskalofrío)', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 0, '2021-06-14T17:17:36Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Gentlemen Broncos', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, 0, '2021-09-29T05:53:07Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Dear Diary (Caro Diario)', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, 0, '2021-08-21T05:17:55Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('First Man Into Space', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, 0, '2021-04-11T12:34:04Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Neighbors', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, 0, '2021-09-26T14:10:45Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Mirror Has Two Faces, The', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, 0, '2021-03-13T00:19:33Z');
        insert into post (title, text, "creatorId", "noteCount", "createdAt") values ('Jin Roh: The Wolf Brigade (Jin-Rô)', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, 0, '2021-08-08T20:23:49Z');
        
        `)
    }

    public async down(__: QueryRunner): Promise<void> {
    }

}
